version: "3.9"  # optional since v1.27.0
services:
  # shorter:
  #   build: .
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   container_name: shorter
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   command: npm start

  mongo:
    image: mongo:4.4.17-rc0
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: shorter_dev
      MONGO_INITDB_ROOT_PASSWORD: shorter_dev

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: shorter_dev
      ME_CONFIG_MONGODB_ADMINPASSWORD: shorter_dev
      ME_CONFIG_MONGODB_URL: mongodb://shorter_dev:shorter_dev@mongo:27017/
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'